version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test: &build-and-test
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn test
  node-lts:
    <<: *build-and-test
    docker:
      - image: circleci/node:lts-browsers
  node-10:
    <<: *build-and-test
    docker:
      - image: circleci/node:chakracore-10-browsers
  node-8:
    <<: *build-and-test
    docker:
      - image: circleci/node:chakracore-8-browsers
workflows:
    build-and-test:
      jobs:
        - node-lts
        - node-10
        - node-8
